name: PR Validation
on: [ push, pull_request ]

jobs:
  scalaFmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: 17
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Check formatting
        run: sbt scalafmtCheckAll

  test:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: 17
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Compile and test
        run: sbt test
  merge:
    name: Merge dependency update
    if: github.actor == 'scala-steward' || github.actor == 'JannikArndt'
    needs:
      - scalaFmt
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        uses: desbo/merge-pr-action@v0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOWED_UPDATE: minor
          MERGE_METHOD: squash
